# SPDX-FileCopyrightText: Copyright 2025 Chen Linxuan <me@black-desk.cn>
#
# SPDX-License-Identifier: MIT

name: Github action runs commitlint

description: |-
  A GitHub Action runs commitlint with default configuration.
  This action should only be executed on push and pull_request events.

author: Chen Linxuan

branding:
  icon: 'check-circle'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - if: github.event_name != 'pull_request'
      shell: bash
      run: |
        echo "This action should only be executed on pull_request event." >&2
        exit 1
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install and run commitlint CLI
      shell: bash
      run: |
        npm install -g @commitlint/cli @commitlint/config-conventional

        FROM="${{ github.event.push.before }}"
        TO="${{ github.event.push.after }}"

        if [ "${{ github.event_name }}" == "pull_request" ]; then
          FROM="${{ github.event.pull_request.base.sha }}"
          TO="${{ github.event.pull_request.head.sha }}"
        fi

        if [ -z "$FROM" ]; then
          exit 1
        fi

        if [ -z "$TO" ]; then
          exit 1
        fi

        if commitlint --last &>/dev/null; then
          commitlint --verbose --from "$FROM" --to "$TO"
          exit
        fi

        CONFIG="$(mktemp commitlint.config.XXXXXXXXXX.js)"
        echo "Config file of commitlint missing, generate default config at $CONFIG" >&2

        # NOTE: https://github.com/dependabot/dependabot-core/issues/2445#issuecomment-949633412
        cat > "$CONFIG" <<EOF
        module.exports = {
          extends: ['@commitlint/config-conventional'],
          ignores: [(message) => /^Bumps \[.+]\(.+\) from .+ to .+\.$/m.test(message)],
        }
        EOF

        commitlint --verbose --from "$FROM" --to "$TO" --config "$CONFIG"
