# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright 2025 Chen Linxuan <me@black-desk.cn>

name: Continuous integration for golang projects

description: |-
  A GitHub Action for continuous integration of my personal golang projects.

  This action requires following permissions:
    contents: write

author: Chen Linxuan

branding:
  icon: 'check-circle'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: black-desk/workflows/common@master
    - id: tag
      shell: bash
      run: |
        script="./scripts/get-project-version.sh"

        if [ ! -f "$script" ]; then
          script="./tools/get-project-version.sh"
        fi

        if [ ! -f "$script" ]; then
          echo "get-project-version.sh not found" >&2
          exit 1
        fi

        version="$("$scripts")"

        if ! git rev-parse "$version" &>/dev/null; then
          git tag "$version"
          git push --tags
          echo version="$version" >> $GITHUB_OUTPUT
        fi

    - if: steps.tag.outputs.version != ''
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ github.token }}
        CUSTOM_TAG: ${{ steps.tag.outputs.version }}
