# SPDX-FileCopyrightText: Copyright 2025 Chen Linxuan <me@black-desk.cn>
#
# SPDX-License-Identifier: MIT

name: Continuous integration for rust projects

description: |-
  A GitHub Action for continuous integration of my personal Rust projects.

  This action requires following permissions:
    id-token: write
    contents: write

author: Chen Linxuan

branding:
  icon: 'check-circle'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: black-desk/workflows/common@master

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Build and test
      shell: bash
      run: |
        cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

    - uses: black-desk/workflows/codecov@master
