name: Common logic for all actions

description: |-
  A common logic for all gitHub actions in this repository.
  This action should not be used alone.

author: Chen Linxuan

branding:
  icon: 'check-circle'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
