# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright 2025 Chen Linxuan <me@black-desk.cn>

name: Generic github action

description: |-
  This is a generic GitHub Action
  which should be running on all my personal projects
  to keep the code clean.

author: Chen Linxuan

branding:
  icon: 'check-circle'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: black-desk/workflows/common@master
    - uses: black-desk/clean@master
    - uses: fsfe/reuse-action@v5
    - uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - if: github.event_name == 'pull_request'
      uses: black-desk/workflows/commitlint@master
