# SPDX-FileCopyrightText: Copyright 2025 Chen Linxuan <me@black-desk.cn>
#
# SPDX-License-Identifier: MIT

name: Generic github action

description: |-
  This is a generic GitHub Action
  which should be running on all my personal projects
  to keep the code clean.

author: Chen Linxuan

branding:
  icon: 'check-circle'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: black-desk/workflows/common@master
    - name: Lint code with black-desk/clean
      uses: black-desk/clean-action@master
    - name: Lint code with black-desk/up2date
      uses: black-desk/up2date-action@master
    - name: Lint code with REUSE
      uses: fsfe/reuse-action@v6
    - name: Lint code with gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - if: github.event_name == 'pull_request'
      name: Lint commit messages with commitlint
      uses: black-desk/workflows/commitlint@master
