name: Continuous integration for master

on:
  push:
    branches:
      - master

jobs:
  generic:
    name: Generic github action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./generic
